Homework/Models/客戶資料.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 客戶資料
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 客戶資料()
        {
            this.客戶銀行資訊 = new HashSet<客戶銀行資訊>();
            this.客戶聯絡人 = new HashSet<客戶聯絡人>();
        }
    
        public int Id { get; set; }
        public string 客戶名稱 { get; set; }
        public string 統一編號 { get; set; }
        public string 電話 { get; set; }
        public string 傳真 { get; set; }
        public string 地址 { get; set; }
        public string Email { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> 客戶分類Id { get; set; }
        public string 帳號 { get; set; }
        public string 密碼 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶銀行資訊> 客戶銀行資訊 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶聯絡人> 客戶聯絡人 { get; set; }
        public virtual 客戶類別 客戶類別 { get; set; }
    }
}

Homework/Controllers/客戶資料Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClosedXML.Excel;
using Homework.Models;

namespace Homework.Controllers
{
    public class 客戶資料Controller : BaseController
    {
        客戶資料Repository repo;
        客戶銀行資訊Repository bankRepo;
        客戶聯絡人Repository contactRepo;
        客戶類別Repository categoryRepo;

        public 客戶資料Controller()
        {
            repo = RepositoryHelper.Get客戶資料Repository();
            bankRepo = RepositoryHelper.Get客戶銀行資訊Repository(repo.UnitOfWork);
            contactRepo = RepositoryHelper.Get客戶聯絡人Repository(repo.UnitOfWork);
            categoryRepo = RepositoryHelper.Get客戶類別Repository(repo.UnitOfWork);
        }

        [ChildActionOnly]  // 不被使用者直接呼叫
        [HttpGet]
        public ActionResult Details_聯絡人清單(int id)
        {

            ViewData.Model = repo.Find(id).客戶聯絡人.ToList();
            return PartialView("Details_聯絡人清單");
        }

        [HttpPost]
        public ActionResult BatchUpdate(聯絡人批次修改VM[] contact)
        {
            if (ModelState.IsValid)
            {
                foreach (var vm in contact)
                {
                    客戶聯絡人 c = db.客戶聯絡人.Find(vm.Id);
                    c.職稱 = vm.職稱;
                    c.手機 = vm.手機;
                    c.電話 = vm.電話;
                }

                db.SaveChanges();
                return RedirectToAction("Details", new { id = contact[0].客戶Id });
            }
            客戶資料 客戶資料 = repo.Find(contact[0].客戶Id);
            //ViewData.Model = repo.Find(contact[0].客戶Id).客戶聯絡人.ToList();
            return View("Details", 客戶資料);
            //return PartialView("Details_聯絡人清單");
            //return View("Details_聯絡人清單");
        }

        // GET: 客戶資料
        //public ActionResult Index()
        //{
        //    var data = repo.All().AsQueryable();

        //    ViewBag.客戶分類Id = new SelectList(categoryRepo.SelectItem(), "分類Id", "客戶分類", 0);

        //    return View(data.Take(10));
        //}
        [Authorize]
        public ViewResult Index(string sortOrder)
        {
            ViewBag.客戶分類Id = new SelectList(categoryRepo.SelectItem(), "分類Id", "客戶分類", 0);

            ViewBag.客戶名稱Sort = String.IsNullOrEmpty(sortOrder) ? "客戶名稱_desc" : "";
            ViewBag.客戶類別Sort = sortOrder == "客戶類別" ? "客戶類別_desc" : "客戶類別";
            ViewBag.統一編號Sort = sortOrder == "統一編號" ? "統一編號_desc" : "統一編號";
            ViewBag.電話Sort = sortOrder == "電話" ? "電話_desc" : "電話";
            ViewBag.傳真Sort = sortOrder == "傳真" ? "傳真_desc" : "傳真";
            ViewBag.地址Sort = sortOrder == "地址" ? "地址_desc" : "地址";
            ViewBag.EmailSort = sortOrder == "Email" ? "Email_desc" : "Email";

            var data = repo.All().AsQueryable();
            switch (sortOrder)
            {
                case "客戶名稱_desc":
                    data = data.OrderByDescending(w => w.客戶名稱);
                    break;
                case "客戶類別_desc":
                    data = data.OrderByDescending(w => w.客戶分類Id);
                    break;
                case "客戶類別":
                    data = data.OrderBy(w => w.客戶分類Id);
                    break;
                case "統一編號_desc":
                    data = data.OrderByDescending(w => w.統一編號);
                    break;
                case "統一編號":
                    data = data.OrderBy(w => w.統一編號);
                    break;
                case "電話_desc":
                    data = data.OrderByDescending(w => w.電話);
                    break;
                case "電話":
                    data = data.OrderBy(w => w.電話);
                    break;
                case "傳真_desc":
                    data = data.OrderByDescending(w => w.傳真);
                    break;
                case "傳真":
                    data = data.OrderBy(w => w.傳真);
                    break;
                case "地址_desc":
                    data = data.OrderByDescending(w => w.地址);
                    break;
                case "地址":
                    data = data.OrderBy(w => w.地址);
                    break;
                case "Email_desc":
                    data = data.OrderByDescending(w => w.Email);
                    break;
                case "Email":
                    data = data.OrderBy(w => w.Email);
                    break;
                default:
                    data = data.OrderBy(w => w.客戶名稱);
                    break;
            }
            return View(data.Take(10));
        }

        [HttpPost]
        public FileResult Export()
        {
            // ClosedXML的用法 先new一個Excel Workbook
            using (XLWorkbook wb = new XLWorkbook())
            {
                //取得我要塞入Excel內的資料
                var data = repo.All().Select(c => new { c.客戶名稱, c.統一編號, c.電話, c.傳真, c.地址, c.Email }).AsQueryable();
                //一個workbook內至少會有一個worksheet,並將資料Insert至這個位於A1這個位置上
                var ws = wb.Worksheets.Add("客戶聯絡人", 1);

                ws.Cell(1, 1).InsertData(data);

                //因為是用Query的方式,這個地方要用串流的方式來存檔
                using (MemoryStream memoryStream = new MemoryStream())
                {
                    wb.SaveAs(memoryStream);
                    //請注意 一定要加入這行,不然Excel會是空檔
                    memoryStream.Seek(0, SeekOrigin.Begin);
                    //注意Excel的ContentType,是要用這個"application/vnd.ms-excel" 不曉得為什麼網路上有的Excel ContentType超長,xlsx會錯 xls反而不會
                    return this.File(memoryStream.ToArray(), "application/vnd.ms-excel", "Download.xlsx");
                }
            }
        }
        [Authorize]
        public ActionResult Statistics()
        {
            var data = repo.All()
                .Select(c => new 客戶統計ViewModel()
                {
                    Id = c.Id,
                    客戶名稱 = c.客戶名稱
                }).ToList();

            foreach (var item in data)
            {
                item.銀行帳戶數量 = bankRepo.Count(item.Id);
                item.聯絡人數量 = contactRepo.Count(item.Id);
            }

            return View(data);
        }

        [Route("search")]
        public ActionResult Search(string keyword, int 客戶分類Id)
        {
            var data = repo.Search(客戶分類Id, keyword);
            ViewBag.客戶分類Id = new SelectList(categoryRepo.SelectItem(), "分類Id", "客戶分類", 客戶分類Id);

            return View("Index", data);
        }

        // GET: 客戶資料/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶資料 客戶資料 = repo.Find(id.Value);
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }
            return View(客戶資料);
        }

        // GET: 客戶資料/Create
        public ActionResult Create()
        {
            ViewBag.客戶分類Id = new SelectList(categoryRepo.All(), "分類Id", "客戶分類");
            return View();
        }

        // POST: 客戶資料/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,客戶名稱,統一編號,電話,傳真,地址,Email,客戶分類Id")] 客戶資料 客戶資料)
        {
            if (ModelState.IsValid)
            {
                repo.Add(客戶資料);
                repo.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }
            ViewBag.客戶分類Id = new SelectList(categoryRepo.All(), "分類Id", "客戶分類", 客戶資料.客戶分類Id);
            return View(客戶資料);
        }

        // GET: 客戶資料/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            客戶資料 客戶資料 = repo.Find(id.Value);
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }

            ViewBag.客戶分類Id = new SelectList(categoryRepo.All(), "分類Id", "客戶分類", 客戶資料.客戶分類Id);

            return View(客戶資料);
        }

        // POST: 客戶資料/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,客戶名稱,統一編號,電話,傳真,地址,Email,客戶分類Id,帳號,密碼")] 客戶資料 客戶資料)
        {
            if (ModelState.IsValid)
            {
                repo.Update(客戶資料);
                var db = repo.UnitOfWork.Context;
                db.Entry(客戶資料).State = EntityState.Modified;
                db.SaveChanges(); ;
                return RedirectToAction("Index");
            }
            ViewBag.客戶分類Id = new SelectList(categoryRepo.All(), "分類Id", "客戶分類", 客戶資料.客戶分類Id);

            return View(客戶資料);
        }

        // GET: 客戶資料/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶資料 客戶資料 = db.客戶資料.Find(id);
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }
            return View(客戶資料);
        }

        // POST: 客戶資料/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            客戶資料 客戶資料 = repo.Find(id);
            repo.Delete(客戶資料);
            repo.UnitOfWork.Commit();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repo.UnitOfWork.Context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Homework/Views/客戶資料/Create.cshtml
@model Homework.Models.客戶資料

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>客戶資料</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.客戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.客戶名稱, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.客戶名稱, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.客戶分類Id, "客戶分類Id", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("客戶分類Id", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.客戶分類Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.統一編號, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.統一編號, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.統一編號, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.傳真, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.傳真, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.傳真, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.地址, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.地址, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.地址, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.帳號, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.帳號, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.帳號, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.密碼, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.密碼, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.密碼, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Homework/Views/客戶資料/Delete.cshtml
@model Homework.Models.客戶資料

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>客戶資料</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.統一編號)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.統一編號)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.傳真)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.傳真)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.地址)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.地址)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Homework/Views/客戶資料/Details.cshtml
@model Homework.Models.客戶資料

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>客戶資料</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.客戶名稱)
        </dd>

        <dt>
            @Html.DisplayFor(model => model.客戶類別.客戶分類)
        </dt>
        <dd>
            @Html.DisplayNameFor(model => model.客戶類別.客戶分類)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.統一編號)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.統一編號)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.傳真)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.傳真)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.地址)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.地址)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<h3>客戶聯絡人</h3>
@*@Html.Action("Details_聯絡人清單", new { id = Model.Id })*@
@Html.Partial("Details_聯絡人清單", Model.客戶聯絡人.ToList())
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Homework/Views/客戶資料/Details_聯絡人清單.cshtml
@model IEnumerable<Homework.Models.客戶聯絡人>

@{
    ViewBag.Title = "Details_聯絡人清單";
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("BatchUpdate", "客戶資料"))
{
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.職稱)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.姓名)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.手機)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.電話)
        </th>
    </tr>

    @{
        var contact = Model.ToArray();
    }

    @for (int i = 0; i < contact.Length; i++)
    {
        @Html.HiddenFor(modelItem => contact[i].Id)
        @Html.HiddenFor(modelItem => contact[i].客戶Id)
        <tr>
            <td>
                @* <input type="text" name="[0].職稱" value='@data[i].職稱' />*@
                @Html.EditorFor(modelItem => contact[i].職稱, new { Name = "data.職稱" })
                @Html.ValidationMessageFor(model => contact[i].職稱, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.DisplayFor(modelItem => contact[i].姓名)
            </td>
            <td>
                @Html.DisplayFor(modelItem => contact[i].Email)
            </td>
            <td>
                @Html.EditorFor(modelItem => contact[i].手機)
                @Html.ValidationMessageFor(model => contact[i].手機, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.EditorFor(modelItem => contact[i].電話)
                @Html.ValidationMessageFor(model => contact[i].電話, "", new { @class = "text-danger" })
            </td>
        </tr>
    }

</table>

    <input type="submit" />

}

Homework/Views/客戶資料/Index.cshtml
@model IEnumerable<Homework.Models.客戶資料>

@{
    ViewBag.Title = "Index";
}

<h2>客戶資料</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Search", "客戶資料", FormMethod.Get, null))
{
    <div class="form-group">
        @Html.TextBox("keyword", null, new { placeholder = "請輸入關鍵字" })
        <input type="submit" />
    </div>
    <div class="form-group">
        @Html.DropDownList("客戶分類Id", null, htmlAttributes: new { @class = "form-control", onchange = "this.form.submit();" })
    </div>
}
@using (Html.BeginForm("Export", "客戶資料", FormMethod.Post))
{
    <input type="submit" value="Export" />
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink(Html.DisplayNameFor(model => model.客戶名稱).ToHtmlString(), "Index", new { sortOrder = ViewBag.客戶名稱Sort })
        </th>

        <th>
            @Html.ActionLink(Html.DisplayNameFor(model => model.帳號).ToHtmlString(), "Index")
        </th>

        <th>
            @Html.ActionLink(Html.DisplayNameFor(model => model.客戶類別.客戶分類).ToHtmlString(), "Index", new { sortOrder = ViewBag.客戶類別Sort })
        </th>
        <th>
            @Html.ActionLink(Html.DisplayNameFor(model => model.統一編號).ToHtmlString(), "Index", new { sortOrder = ViewBag.統一編號Sort })
        </th>
        <th>
            @Html.ActionLink(Html.DisplayNameFor(model => model.電話).ToHtmlString(), "Index", new { sortOrder = ViewBag.電話Sort })
        </th>
        <th>
            @Html.ActionLink(Html.DisplayNameFor(model => model.傳真).ToHtmlString(), "Index", new { sortOrder = ViewBag.傳真Sort })
        </th>
        <th>
            @Html.ActionLink(Html.DisplayNameFor(model => model.地址).ToHtmlString(), "Index", new { sortOrder = ViewBag.地址Sort })
        </th>
        <th>
            @Html.ActionLink(Html.DisplayNameFor(model => model.Email).ToHtmlString(), "Index", new { sortOrder = ViewBag.EmailSort })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.客戶名稱)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.帳號)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.客戶類別.客戶分類)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.統一編號)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.電話)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.傳真)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.地址)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
    }

</table>

Homework/Views/客戶資料/Statistics.cshtml
@model IEnumerable<Homework.Models.客戶統計ViewModel>

@{
    ViewBag.Title = "statistics";
}

<h2>statistics</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.聯絡人數量)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.銀行帳戶數量)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.客戶名稱)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.聯絡人數量)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.銀行帳戶數量)
        </td>
    </tr>
}

</table>